### PR TITLE
Update manifest with namespace and variable for package name

### PR DESCRIPTION
**Pull request by beemarie**

### CODE REVIEW

**Comment by beemarie** [comment]
@csantanapr Please review, if you're fine with package name being a variable, I can update the README.md for CLI before we merge.

**Comment by beemarie** [comment]
jshint wasn't actually being run on this repo -- I removed the npm install, and created a new issue to actually run jshint against this & other template repos:
https://github.com/ibm-functions/template-cloud-object-storage/issues/10

**Comment by csantanapr** [comment]
Maybe it can be a new convention in the manifest or wskdeploy flag

**Comment by csantanapr** [comment]
—override-package cloud-object-storage newname-object-store-pkg ?

**Comment by csantanapr** [comment]
Or maybe we have two manifests one for CLI and one for UI?

**Comment by beemarie** [comment]
From the UI, we decided to give the user the ability to change the package name on creation because you can't rename a package name after it's created.  That same idea applies to using a template from the CLI.

That said, I can understand not wanting to ask users to make too many decisions.  The command to deploy the manifest looks like this right now: `PACKAGE_NAME=cloud-object-storage wskdeploy`

@csantanapr I think defaults in the manifest are an interesting idea.  So something like:
$PACKAGE_NAME--my_default_name:
If $PACKAGE_NAME wasn't provided then it will default to something.

**Pull request merged**
